version: "3.9"

services:
  qdrant:
    image: qdrant/qdrant
    container_name: qdrant_custom
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - "C:/docker_composes/qdrant_storage/qdrant_storage:/qdrant/storage"
    restart: unless-stopped
